Repository deepgarg-visa/datahub, pull requests merged in 2024-04, with the labels that each got.

#30 Business Attributes: UI Schema Field Entity Changes
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTable.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/FieldAttribute.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/FieldDescription.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/useBusinessAttributeRenderer.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/useDescriptionRenderer.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/useTagsAndTermsRenderer.tsx
  datahub-web-react/src/app/shared/businessAttribute/AttributeContent.tsx
  datahub-web-react/src/app/shared/businessAttribute/BusinessAttributeGroup.tsx
Labels: product, community-contribution

#31 Business Attributes: UI Show|Hide Feature Flag Implementation | Modified Test Cases
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/config/AppConfigResolver.java
  datahub-graphql-core/src/main/resources/app.graphql
  datahub-web-react/src/Mocks.tsx
  datahub-web-react/src/app/SearchRoutes.tsx
  datahub-web-react/src/app/businessAttribute/BusinessAttributes.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/AccessManagement/__tests__/AccessManagement.test.ts
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/SchemaTable.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/FieldAttribute.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/components/SchemaFieldDrawer/SchemaFieldDrawer.tsx
  datahub-web-react/src/app/entity/shared/tabs/Dataset/Schema/utils/useBusinessAttributeRenderer.tsx
  datahub-web-react/src/app/home/HomePageRecommendations.tsx
  datahub-web-react/src/app/shared/admin/HeaderLinks.tsx
  datahub-web-react/src/app/shared/businessAttribute/AddBusinessAttributeModal.tsx
  datahub-web-react/src/app/shared/businessAttribute/AttributeContent.tsx
  datahub-web-react/src/app/useAppConfig.ts
  datahub-web-react/src/appConfigContext.tsx
  datahub-web-react/src/graphql/app.graphql
  smoke-test/tests/cypress/cypress/e2e/businessAttribute/attribute_mutations.js
  smoke-test/tests/cypress/cypress/e2e/businessAttribute/businessAttribute.js
  smoke-test/tests/cypress/cypress/e2e/mutations/mutations.js
  smoke-test/tests/cypress/cypress/support/commands.js
Labels: product, community-contribution, smoke_test

#32 feat(search): Add SchemaFieldEntity to search functionality
  datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/search/SearchUtils.java
  datahub-web-react/src/app/buildEntityRegistry.ts
  datahub-web-react/src/app/entity/schemaField/SchemaFieldPropertiesEntity.tsx
  datahub-web-react/src/app/entity/schemaField/preview/Preview.tsx
  datahub-web-react/src/graphql/search.graphql
Labels: product, community-contribution

#33 Business Attributes: Customized URNs Support for Business Attributes
  datahub-web-react/src/app/businessAttribute/CreateBusinessAttributeModal.tsx
Labels: product, community-contribution

#34 Business Attributes: Fixed Schema Field Cypress Test Cases
  datahub-web-react/src/app/entity/schemaField/preview/Preview.tsx
  smoke-test/tests/cypress/cypress/e2e/businessAttribute/businessAttribute.js
  smoke-test/tests/cypress/cypress/e2e/mutations/mutations.js
Labels: product, community-contribution, smoke_test

#38 feat(search/schema_field): Update schema field card in search results
  datahub-web-react/src/app/entity/schemaField/SchemaFieldPropertiesEntity.tsx
  datahub-web-react/src/app/entity/schemaField/preview/Preview.tsx
Labels: product, community-contribution

#36 Business Attributes: Feature Flag Cypress Test Cases Fix
  smoke-test/tests/cypress/cypress/e2e/businessAttribute/attribute_mutations.js
  smoke-test/tests/cypress/cypress/e2e/businessAttribute/businessAttribute.js
  smoke-test/tests/cypress/cypress/e2e/home/home.js
  smoke-test/tests/cypress/cypress/e2e/mutations/mutations.js
Labels: community-contribution, smoke_test

#37 business-attribute-flag-for-openapi
  buildSrc/build.gradle
  buildSrc/src/main/java/io/datahubproject/OpenApiEntities.java
  metadata-service/openapi-entity-servlet/src/main/java/io/datahubproject/openapi/v2/delegates/EntityApiDelegateImpl.java
Labels: devops, community-contribution
